"""empty message

Revision ID: 29aa39e4f35c
Revises: 5b7dddbe90a2
Create Date: 2017-03-20 13:51:29.055742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29aa39e4f35c'
down_revision = '5b7dddbe90a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dosage', 'medicine', ['medicine_id'], ['id'])
    op.create_foreign_key(None, 'dosage', 'unit', ['unit_id'], ['id'])
    op.create_foreign_key(None, 'dosage', 'dosage_type', ['dosage_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dosage', type_='foreignkey')
    op.drop_constraint(None, 'dosage', type_='foreignkey')
    op.drop_constraint(None, 'dosage', type_='foreignkey')
    # ### end Alembic commands ###
