"""empty message

Revision ID: 3b45ba98f52f
Revises: 0dd22256e6b5
Create Date: 2017-03-21 06:37:39.344847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b45ba98f52f'
down_revision = '0dd22256e6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dosage', 'medicine', ['medicine_id'], ['id'])
    op.create_foreign_key(None, 'dosage', 'unit', ['unit_id'], ['id'])
    op.create_foreign_key(None, 'dosage', 'dosage_type', ['dosage_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dosage', type_='foreignkey')
    op.drop_constraint(None, 'dosage', type_='foreignkey')
    op.drop_constraint(None, 'dosage', type_='foreignkey')
    # ### end Alembic commands ###
