"""empty message

Revision ID: 9328ce548f62
Revises: 3b45ba98f52f
Create Date: 2017-03-21 09:28:48.846841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9328ce548f62'
down_revision = '3b45ba98f52f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'dosage', 'medicine', ['medicine_id'], ['id'])
    op.create_foreign_key(None, 'dosage', 'unit', ['unit_id'], ['id'])
    op.create_foreign_key(None, 'dosage', 'dosage_type', ['dosage_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dosage', type_='foreignkey')
    op.drop_constraint(None, 'dosage', type_='foreignkey')
    op.drop_constraint(None, 'dosage', type_='foreignkey')
    # ### end Alembic commands ###
