"""empty message

Revision ID: f05e04284523
Revises: aaa730cc3ae2
Create Date: 2017-03-19 12:29:52.136937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f05e04284523'
down_revision = 'aaa730cc3ae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animal_type_name'), 'animal_type', ['name'], unique=True)
    op.create_table('medicine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('descr', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_title'), 'medicine', ['title'], unique=True)
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_name'), 'unit', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_name'), table_name='unit')
    op.drop_table('unit')
    op.drop_index(op.f('ix_medicine_title'), table_name='medicine')
    op.drop_table('medicine')
    op.drop_index(op.f('ix_animal_type_name'), table_name='animal_type')
    op.drop_table('animal_type')
    # ### end Alembic commands ###
